### ISSUE TITLE
[USART_STM32.c] macros UART_WORDLENGTH_7B, UART_STOPBITS_1_5, UART_STOPBITS_0_5 not available for STM32F4 series

### ISSUE THREAD

**Issue by GuentherMartin** [Open-CMSIS-Pack/CMSIS-Driver_STM32#11]
STM32F4 series:

Macros UART_WORDLENGTH_7B, UART_STOPBITS_1_5, UART_STOPBITS_0_5 are not defined in STM32F4 HAL Driver include files.

I used the latest STM32F4 CubeMX FW pack STM32Cube_FW_F4_V1.28.0.

**Comment by MiloradCvjetkovic** [comment]
This is addressed in commit e5d98cf863696493ac4c64e86d736d5889228050 .
