### ISSUE TITLE
Add  <requirements> <targets> to PDSC file

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/CMSIS-Driver_STM32#2]
List the supported STM32 Device Families using [/package/requirements/targets](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/element_requirements_pg.html#element_targets) in the PDSC file

**Comment by MiloradCvjetkovic** [comment]
This was added in 333445bdc38989b2498db6685e1e6a7e57735083
