### ISSUE TITLE
ETH_DMATXNDESCWBF_OWN inconsistent accross device series

### ISSUE THREAD

**Issue by ZigaMahne** [Open-CMSIS-Pack/CMSIS-Driver_STM32#4]
STM32F7 series:
- ETH_DMATXNDESCWBF_OWN define is missing
- ETH_DMATXDESC_OWN define for DMA Tx descriptor status register
 
If "Transmitter is busy" checking is necessary in ETH_MAC_STM32 driver then it should be implemented in a generic way.

**Comment by MiloradCvjetkovic** [comment]
Fixed in commit https://github.com/Open-CMSIS-Pack/CMSIS-Driver_STM32/commit/5b8d8a478c6473ad8bbe468bcc90f4d989afdfae
