### ISSUE TITLE
[SPI_STM32.c] INFO_WO_NSS_DEFINE macro inconsistent accross device series

### ISSUE THREAD

**Issue by ZigaMahne** [Open-CMSIS-Pack/CMSIS-Driver_STM32#9]
STM32F7 series:

**INFO_WO_NSS_DEFINE** macro expect _RCC_PERIPHCLK_SPI#_ define from HAL drivers,
stm32f7xx_hal_rcc_ex.h use _RCC_PERIPHCLK_SPDIFRX_ define instead of what expected from **INFO_WO_NSS_DEFINE** macro.

**Comment by MiloradCvjetkovic** [comment]
This is addressed in commit e82c911372b9e0617aae0cac5893b4f984632ce7 .
